---

- name: install postgres and needed dependencies
  apt:
    name: ['postgresql', 'postgresql-contrib', 'libpq-dev', 'python-psycopg2', 'unzip']
    state: present
    update_cache: yes

- name: create sonar postgres user
  become_user: postgres
  postgresql_user:
    name: "{{ sonar_db_user }}"
    password: "{{ sonar_db_password }}"

- name: create sonar postgres db
  become_user: postgres
  postgresql_db:
    name: "{{ sonar_db_name }}"
    owner: "{{ sonar_db_user }}"
